/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hobbyteca.vista;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import hobbyteca.controlador.ControladorAñadirComic;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class AñadirComic extends javax.swing.JDialog {

    private final ControladorAñadirComic controladorAñadirComic;

    /**
     * Creates new form AñadirComic
     * @param parent
     * @param modal
     */
    public AñadirComic(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorAñadirComic = new ControladorAñadirComic(this);
                    Calendar fecha = Calendar.getInstance();
        int annoActual=fecha.get(Calendar.YEAR);
//creamos un modeloDeCombobox 
        
        DefaultComboBoxModel MiModelo= new DefaultComboBoxModel();
        //le decimos hasta que fecha queremos llegar
        for( int fechaInicio=1827;fechaInicio<=annoActual;fechaInicio++){
            String annadirFecha=""+fechaInicio;
        MiModelo.addElement(annadirFecha);
        }
       jComboBoxLanzamiento.setModel(MiModelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelDirector = new javax.swing.JLabel();
        jTextFieldDirector = new javax.swing.JTextField();
        jLabelProductora = new javax.swing.JLabel();
        jTextFieldProdutora = new javax.swing.JTextField();
        jLabelLanzamiento = new javax.swing.JLabel();
        jComboBoxLanzamiento = new javax.swing.JComboBox();
        jLabelGenero = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabelDescripcion = new javax.swing.JLabel();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabelNumerosTotales = new javax.swing.JLabel();
        jTextFieldNumerosTotales = new javax.swing.JTextField();
        jLabelCaracteresMaximos = new javax.swing.JLabel();
        jButtonAnnadir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMensage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Comic");

        jLabelTitulo.setText("*Titulo");

        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabelDirector.setText("*Director");

        jTextFieldDirector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDirectorKeyTyped(evt);
            }
        });

        jLabelProductora.setText("*Productora");

        jTextFieldProdutora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProdutoraKeyTyped(evt);
            }
        });

        jLabelLanzamiento.setText("*Lanzamiento");

        jComboBoxLanzamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1888", "1889", "1890", "1891", "1892", "1893", "1894", "1895", "1896", "1897", "1898", "1899", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        jLabelGenero.setText("*Genero");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "humor", "superheroes", "fantasia", "sobrenatural", "detectivesca", "belico", "historico", "erotico", "aventura", "infantil", "terror", "accion" }));

        jLabelDescripcion.setText("*Descripción");

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextAreaDescripcionCaretUpdate(evt);
            }
        });
        jTextAreaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaDescripcionKeyTyped(evt);
            }
        });
        jScrollPaneDescripcion.setViewportView(jTextAreaDescripcion);

        jLabelNumerosTotales.setText("*ComicTotales");

        jTextFieldNumerosTotales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumerosTotalesKeyTyped(evt);
            }
        });

        jLabelCaracteresMaximos.setText("0/3000");

        jButtonAnnadir.setText("Añadir");
        jButtonAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelMensage.setForeground(new java.awt.Color(126, 126, 126));
        jLabelMensage.setText("Todos los campos con \"*\" son obligatorios");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnnadir)
                        .addGap(93, 93, 93)
                        .addComponent(jButtonCancelar)
                        .addGap(14, 14, 14))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDescripcion)
                            .addComponent(jLabelGenero)
                            .addComponent(jLabelLanzamiento)
                            .addComponent(jLabelProductora)
                            .addComponent(jLabelDirector)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelNumerosTotales))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDirector)
                            .addComponent(jTextFieldTitulo)
                            .addComponent(jTextFieldProdutora)
                            .addComponent(jScrollPaneDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(jComboBoxLanzamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumerosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCaracteresMaximos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabelMensage)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCaracteresMaximos)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTitulo)
                                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabelDirector))
                            .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProductora)
                            .addComponent(jTextFieldProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLanzamiento)
                            .addComponent(jComboBoxLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGenero)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabelDescripcion)))))
                .addGap(10, 10, 10)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumerosTotales)
                    .addComponent(jTextFieldNumerosTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabelMensage)
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnadir)
                    .addComponent(jButtonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaDescripcionCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionCaretUpdate
        controladorAñadirComic.contadorTextArea();
    }//GEN-LAST:event_jTextAreaDescripcionCaretUpdate

    private void jTextAreaDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionKeyTyped
        controladorAñadirComic.caracteresMaximosTextArea(evt, 3000, jTextAreaDescripcion);
    }//GEN-LAST:event_jTextAreaDescripcionKeyTyped

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
        controladorAñadirComic.caracteresMaximos(evt, 100, jTextFieldTitulo);
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jTextFieldDirectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDirectorKeyTyped
        controladorAñadirComic.caracteresMaximos(evt, 100, jTextFieldDirector);
    }//GEN-LAST:event_jTextFieldDirectorKeyTyped

    private void jTextFieldProdutoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProdutoraKeyTyped
        controladorAñadirComic.caracteresMaximos(evt, 100, jTextFieldProdutora);
    }//GEN-LAST:event_jTextFieldProdutoraKeyTyped

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirActionPerformed
        String titulo = jTextFieldTitulo.getText();
        String director = jTextFieldDirector.getText();
        String productora = jTextFieldProdutora.getText();
        String lanzamiento = new String((String) jComboBoxLanzamiento.getSelectedItem());
        String genero = new String((String) jComboBoxGenero.getSelectedItem());
        String descripcion = jTextAreaDescripcion.getText();
        String numerosTotales=jTextFieldNumerosTotales.getText();
        
            switch (controladorAñadirComic.comprobarCamposRellenos(titulo, director, productora, descripcion,numerosTotales )) {
                case 0:
                    JOptionPane.showMessageDialog(this, "Rellene todos los campos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
                    break;

     
                case 2: {
                    try {
                        if (controladorAñadirComic.insertarComic(titulo, director, productora, lanzamiento, genero, descripcion,numerosTotales)) {
                            JOptionPane.showMessageDialog(this, "Se ha guardado Correctamente", "Info", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se ha guardado", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error con la bdd contacte con el administrador", "Error inesperado", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(AñadirComic.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                //guardarComicConTrailer
                break;
                case 3:
                    JOptionPane.showMessageDialog(this, "Titulo ya existente. "
                            + "Si es una remasterización por favor pongala con el año entre parentesis detras del titulo", "Error", JOptionPane.ERROR_MESSAGE);
                    
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Si ves este mensaje es que has tocado el codigo por favor dejalo como estaba y no vuevas edites nada", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                    
            }
      


    }//GEN-LAST:event_jButtonAnnadirActionPerformed

    private void jTextFieldNumerosTotalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumerosTotalesKeyTyped
       controladorAñadirComic.caracteresMaximos(evt, 5, jTextFieldNumerosTotales);
       controladorAñadirComic.limitarNumeros(evt);
    }//GEN-LAST:event_jTextFieldNumerosTotalesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirComic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirComic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirComic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirComic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirComic dialog = new AñadirComic(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JComboBox getjComboBoxGenero() {
        return jComboBoxGenero;
    }

    public void setjComboBoxGenero(JComboBox jComboBoxGenero) {
        this.jComboBoxGenero = jComboBoxGenero;
    }

    public JComboBox getjComboBoxLanzamiento() {
        return jComboBoxLanzamiento;
    }

    public void setjComboBoxLanzamiento(JComboBox jComboBoxLanzamiento) {
        this.jComboBoxLanzamiento = jComboBoxLanzamiento;
    }

    public JLabel getjLabelCaracteresMaximos() {
        return jLabelCaracteresMaximos;
    }

    public void setjLabelCaracteresMaximos(JLabel jLabelCaracteresMaximos) {
        this.jLabelCaracteresMaximos = jLabelCaracteresMaximos;
    }

    public JScrollPane getjScrollPaneDescripcion() {
        return jScrollPaneDescripcion;
    }

    public void setjScrollPaneDescripcion(JScrollPane jScrollPaneDescripcion) {
        this.jScrollPaneDescripcion = jScrollPaneDescripcion;
    }

    public JTextArea getjTextAreaDescripcion() {
        return jTextAreaDescripcion;
    }

    public void setjTextAreaDescripcion(JTextArea jTextAreaDescripcion) {
        this.jTextAreaDescripcion = jTextAreaDescripcion;
    }

    public JTextField getjTextFieldDirector() {
        return jTextFieldDirector;
    }

    public void setjTextFieldDirector(JTextField jTextFieldDirector) {
        this.jTextFieldDirector = jTextFieldDirector;
    }

    public JTextField getjTextFieldProdutora() {
        return jTextFieldProdutora;
    }

    public void setjTextFieldProdutora(JTextField jTextFieldProdutora) {
        this.jTextFieldProdutora = jTextFieldProdutora;
    }

    public JTextField getjTextFieldTitulo() {
        return jTextFieldTitulo;
    }

    public void setjTextFieldTitulo(JTextField jTextFieldTitulo) {
        this.jTextFieldTitulo = jTextFieldTitulo;
    }

    public JTextField getjTextFieldNumerosTotales() {
        return jTextFieldNumerosTotales;
    }

    public void setjTextFieldNumerosTotales(JTextField jTextFieldNumerosTotales) {
        this.jTextFieldNumerosTotales = jTextFieldNumerosTotales;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnadir;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxLanzamiento;
    private javax.swing.JLabel jLabelCaracteresMaximos;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLanzamiento;
    private javax.swing.JLabel jLabelMensage;
    private javax.swing.JLabel jLabelNumerosTotales;
    private javax.swing.JLabel jLabelProductora;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldNumerosTotales;
    private javax.swing.JTextField jTextFieldProdutora;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
