/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hobbyteca.vista;

import javax.swing.JComboBox;
import javax.swing.JLabel;

import javax.swing.JTextField;
import hobbyteca.controlador.ControladorAñadirMusica;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jesus
 */
public class AñadirMusica extends javax.swing.JDialog {

    private final ControladorAñadirMusica controladorAñadirMusica;

    /**
     * Creates new form AñadirMusiac
     * @param parent
     * @param modal
     */
    public AñadirMusica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorAñadirMusica = new ControladorAñadirMusica(this);
            Calendar fecha = Calendar.getInstance();
        int annoActual=fecha.get(Calendar.YEAR);
//creamos un modeloDeCombobox 
        
        DefaultComboBoxModel MiModelo= new DefaultComboBoxModel();
        //le decimos hasta que fecha queremos llegar
        for( int fechaInicio=1888;fechaInicio<=annoActual;fechaInicio++){
            String annadirFecha=""+fechaInicio;
        MiModelo.addElement(annadirFecha);
        }
       jComboBoxLanzamiento.setModel(MiModelo);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelASIN = new javax.swing.JLabel();
        jTextFieldASIN = new javax.swing.JTextField();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelAlbum = new javax.swing.JLabel();
        jTextFieldAlbum = new javax.swing.JTextField();
        jLabelDiscografica = new javax.swing.JLabel();
        jTextFieldDiscografica = new javax.swing.JTextField();
        jLabelLanzamiento = new javax.swing.JLabel();
        jComboBoxLanzamiento = new javax.swing.JComboBox();
        jLabelGenero = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabelTrailer = new javax.swing.JLabel();
        jTextFieldEnlace = new javax.swing.JTextField();
        jButtonAnnadir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Musica");

        jLabelTitulo.setText("*Titulo");

        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jLabelASIN.setText("*ASIN:");

        jTextFieldASIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldASINKeyTyped(evt);
            }
        });

        jLabelAutor.setText("*autor");

        jTextFieldAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAutorKeyTyped(evt);
            }
        });

        jLabelAlbum.setText("*Album:");

        jTextFieldAlbum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAlbumKeyTyped(evt);
            }
        });

        jLabelDiscografica.setText("*Discografica");

        jTextFieldDiscografica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiscograficaKeyTyped(evt);
            }
        });

        jLabelLanzamiento.setText("*Lanzamiento");

        jComboBoxLanzamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1888", "1889", "1890", "1891", "1892", "1893", "1894", "1895", "1896", "1897", "1898", "1899", "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035" }));

        jLabelGenero.setText("*Genero");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "rock", "pop", "electronica", "rap", "instrumental", "salsa", "jazz", "country", "hip-hop", "clasica" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        jLabelTrailer.setText("Enlace:");

        jTextFieldEnlace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEnlaceKeyTyped(evt);
            }
        });

        jButtonAnnadir.setText("Añadir");
        jButtonAnnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnadirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(126, 126, 126));
        jLabel1.setText("Todos los campos con \"*\" son obligatorios");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAlbum)
                            .addComponent(jLabelTitulo)
                            .addComponent(jLabelASIN)
                            .addComponent(jLabelAutor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDiscografica, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelLanzamiento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelTrailer)
                                .addComponent(jLabelGenero)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71))
                            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDiscografica)
                                    .addComponent(jTextFieldEnlace)
                                    .addComponent(jComboBoxLanzamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelContenedorLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldAutor)
                                .addComponent(jTextFieldTitulo)
                                .addComponent(jTextFieldASIN)
                                .addComponent(jTextFieldAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jButtonAnnadir)
                        .addGap(93, 93, 93)
                        .addComponent(jButtonCancelar)))
                .addGap(43, 43, 43))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jLabelASIN)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jTextFieldASIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAutor))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlbum)
                    .addComponent(jTextFieldAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiscografica)
                    .addComponent(jTextFieldDiscografica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLanzamiento)
                    .addComponent(jComboBoxLanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrailer))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnadir)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
        controladorAñadirMusica.caracteresMaximos(evt, 100, jTextFieldTitulo);
    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jTextFieldAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAutorKeyTyped
        controladorAñadirMusica.caracteresMaximos(evt, 100, jTextFieldAutor);
    }//GEN-LAST:event_jTextFieldAutorKeyTyped

    private void jTextFieldDiscograficaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiscograficaKeyTyped
        controladorAñadirMusica.caracteresMaximos(evt, 100, jTextFieldDiscografica);
    }//GEN-LAST:event_jTextFieldDiscograficaKeyTyped

    private void jTextFieldEnlaceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEnlaceKeyTyped
        controladorAñadirMusica.caracteresMaximos(evt, 300, jTextFieldEnlace);
    }//GEN-LAST:event_jTextFieldEnlaceKeyTyped

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAnnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnadirActionPerformed
        String titulo = jTextFieldTitulo.getText();
        String ASIN = jTextFieldASIN.getText();
        String autor = jTextFieldAutor.getText();
        String discografica = jTextFieldDiscografica.getText();
        String lanzamiento = new String((String) jComboBoxLanzamiento.getSelectedItem());
        String genero = new String((String) jComboBoxGenero.getSelectedItem());
        String enlace = jTextFieldEnlace.getText();
        String album = jTextFieldAlbum.getText();
        if(ASIN.length()<10){
             JOptionPane.showMessageDialog(this, "ASIN debe tener 10 carcateres", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            switch (controladorAñadirMusica.comprobarCamposRellenos( ASIN, titulo, autor, discografica, album ,enlace)) {
                case 0:
                    JOptionPane.showMessageDialog(this, "Rellene todos los campos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                case 1: {
                    try {
                        if (controladorAñadirMusica.insertarMusica(ASIN, titulo, autor, discografica, lanzamiento, genero, album , null)) {
                            JOptionPane.showMessageDialog(this, "Se ha guardado Correctamente sin Trailer", "Info", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se ha guardado", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                         JOptionPane.showMessageDialog(this, "Titulo repetido."
                                 + "Si es una remasterización por favor ponga al final del titulo el año entre parentesis", "Error", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(AñadirMusica.class.getName()).log(Level.SEVERE, null, ex);//borrar antes de entregar
                    }
                }
                
                //guardarPeliculaSinTrailer
                break;
                case 2: {
                    try {
                        if (controladorAñadirMusica.insertarMusica(ASIN, titulo, autor, discografica, lanzamiento, genero, album ,enlace)) {
                            JOptionPane.showMessageDialog(this, "Se ha guardado Correctamente", "Info", JOptionPane.INFORMATION_MESSAGE);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "No se ha guardado", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error con la bdd contacte con el administrador", "Error inesperado", JOptionPane.ERROR_MESSAGE);
                        Logger.getLogger(AñadirMusica.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                //guardarMusicaConEnlace
                break;
                case 3:
                    JOptionPane.showMessageDialog(this, "Titulo ya existente. "
                            + "Si es una remasterización por favor pongala con el año entre parentesis detras del titulo", "Error", JOptionPane.ERROR_MESSAGE);
                    
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Si ves este mensaje es que has tocado el codigo por favor dejalo como estaba y no vuevas edites nada", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                    
            }}
    }//GEN-LAST:event_jButtonAnnadirActionPerformed

    private void jTextFieldASINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldASINKeyTyped
        controladorAñadirMusica.caracteresMaximos(evt, 10, jTextFieldASIN);
    }//GEN-LAST:event_jTextFieldASINKeyTyped

    private void jTextFieldAlbumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlbumKeyTyped
       controladorAñadirMusica.caracteresMaximos(evt, 100, jTextFieldASIN);
    }//GEN-LAST:event_jTextFieldAlbumKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AñadirMusica dialog = new AñadirMusica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getjButtonAnnadir() {
        return jButtonAnnadir;
    }

    public void setjButtonAnnadir(JButton jButtonAnnadir) {
        this.jButtonAnnadir = jButtonAnnadir;
    }

    public JButton getjButtonCancelar() {
        return jButtonCancelar;
    }

    public void setjButtonCancelar(JButton jButtonCancelar) {
        this.jButtonCancelar = jButtonCancelar;
    }

    public JComboBox getjComboBoxGenero() {
        return jComboBoxGenero;
    }

    public void setjComboBoxGenero(JComboBox jComboBoxGenero) {
        this.jComboBoxGenero = jComboBoxGenero;
    }

    public JComboBox getjComboBoxLanzamiento() {
        return jComboBoxLanzamiento;
    }

    public void setjComboBoxLanzamiento(JComboBox jComboBoxLanzamiento) {
        this.jComboBoxLanzamiento = jComboBoxLanzamiento;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabelASIN() {
        return jLabelASIN;
    }

    public void setjLabelASIN(JLabel jLabelASIN) {
        this.jLabelASIN = jLabelASIN;
    }

    public JLabel getjLabelAlbum() {
        return jLabelAlbum;
    }

    public void setjLabelAlbum(JLabel jLabelAlbum) {
        this.jLabelAlbum = jLabelAlbum;
    }

    public JLabel getjLabelAutor() {
        return jLabelAutor;
    }

    public void setjLabelAutor(JLabel jLabelAutor) {
        this.jLabelAutor = jLabelAutor;
    }

    public JLabel getjLabelDiscografica() {
        return jLabelDiscografica;
    }

    public void setjLabelDiscografica(JLabel jLabelDiscografica) {
        this.jLabelDiscografica = jLabelDiscografica;
    }

    public JLabel getjLabelGenero() {
        return jLabelGenero;
    }

    public void setjLabelGenero(JLabel jLabelGenero) {
        this.jLabelGenero = jLabelGenero;
    }

    public JLabel getjLabelLanzamiento() {
        return jLabelLanzamiento;
    }

    public void setjLabelLanzamiento(JLabel jLabelLanzamiento) {
        this.jLabelLanzamiento = jLabelLanzamiento;
    }

    public JLabel getjLabelTitulo() {
        return jLabelTitulo;
    }

    public void setjLabelTitulo(JLabel jLabelTitulo) {
        this.jLabelTitulo = jLabelTitulo;
    }

    public JLabel getjLabelTrailer() {
        return jLabelTrailer;
    }

    public void setjLabelTrailer(JLabel jLabelTrailer) {
        this.jLabelTrailer = jLabelTrailer;
    }

    public JPanel getjPanelContenedor() {
        return jPanelContenedor;
    }

    public void setjPanelContenedor(JPanel jPanelContenedor) {
        this.jPanelContenedor = jPanelContenedor;
    }

    public JTextField getjTextFieldASIN() {
        return jTextFieldASIN;
    }

    public void setjTextFieldASIN(JTextField jTextFieldASIN) {
        this.jTextFieldASIN = jTextFieldASIN;
    }

    public JTextField getjTextFieldAlbum() {
        return jTextFieldAlbum;
    }

    public void setjTextFieldAlbum(JTextField jTextFieldAlbum) {
        this.jTextFieldAlbum = jTextFieldAlbum;
    }

    public JTextField getjTextFieldAutor() {
        return jTextFieldAutor;
    }

    public void setjTextFieldAutor(JTextField jTextFieldAutor) {
        this.jTextFieldAutor = jTextFieldAutor;
    }

    public JTextField getjTextFieldDiscografica() {
        return jTextFieldDiscografica;
    }

    public void setjTextFieldDiscografica(JTextField jTextFieldDiscografica) {
        this.jTextFieldDiscografica = jTextFieldDiscografica;
    }

    public JTextField getjTextFieldEnlace() {
        return jTextFieldEnlace;
    }

    public void setjTextFieldEnlace(JTextField jTextFieldEnlace) {
        this.jTextFieldEnlace = jTextFieldEnlace;
    }

    public JTextField getjTextFieldTitulo() {
        return jTextFieldTitulo;
    }

    public void setjTextFieldTitulo(JTextField jTextFieldTitulo) {
        this.jTextFieldTitulo = jTextFieldTitulo;
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnadir;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxLanzamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelASIN;
    private javax.swing.JLabel jLabelAlbum;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelDiscografica;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLanzamiento;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTrailer;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JTextField jTextFieldASIN;
    private javax.swing.JTextField jTextFieldAlbum;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldDiscografica;
    private javax.swing.JTextField jTextFieldEnlace;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
