/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hobbyteca.vista;

import hobbyteca.controlador.UsuarioControladorLoginEventos;
import hobbyteca.controlador.UsuarioControladorLogin;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import hobbyteca.controlador.ConexionControlador;
import javax.swing.JOptionPane;
/**
 *
 * @author jesus
 */
public class Login extends javax.swing.JFrame {

    private final UsuarioControladorLogin UsuarioControlador;
    private final UsuarioControladorLoginEventos UsuarioControladorEventos;
    private ConexionControlador conexsionControlador;
    /**
     * Creates new form Login Atributos en privado. flagNombre para el
     * jTextFieldUsuario flagPassword para el jPasswordFieldPassword
     */
    private boolean flagNombre = false;
    private boolean flagPassword = false;

    /**
     * Constructor con el inicio de todos los componentes. Ponemos el
     * jPasswordFieldPassword con char vacios
     */
    public Login() throws SQLException {
        initComponents();
        jPasswordFieldPassword.setEchoChar((char) 0);
        jButtonLogearse.requestFocus();
        UsuarioControlador = new UsuarioControladorLogin(this);
        UsuarioControladorEventos = new UsuarioControladorLoginEventos(this);
       // this.setDefaultCloseOperation(conexionControlador.cerrarConexion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jButtonLogearse = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jLabelRegistro = new javax.swing.JLabel();
        jCheckBoxVerPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jButtonLogearse.setText("Logeate");
        jButtonLogearse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLogearseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLogearseMouseExited(evt);
            }
        });
        jButtonLogearse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogearseActionPerformed(evt);
            }
        });

        jLabelUsuario.setText("Usuario");

        jTextFieldUsuario.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldUsuario.setText("Usuario");
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });

        jLabelPassword.setText("Password");

        jPasswordFieldPassword.setForeground(new java.awt.Color(126, 126, 126));
        jPasswordFieldPassword.setText("Password");
        jPasswordFieldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldPasswordFocusLost(evt);
            }
        });
        jPasswordFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldPasswordKeyPressed(evt);
            }
        });

        jLabelRegistro.setForeground(new java.awt.Color(0, 0, 240));
        jLabelRegistro.setText("¿No tienes cuenta? Registrate");
        jLabelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRegistroMouseExited(evt);
            }
        });

        jCheckBoxVerPassword.setText("Mostrar Contraseña");
        jCheckBoxVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBoxVerPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBoxVerPasswordMouseExited(evt);
            }
        });
        jCheckBoxVerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVerPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRegistro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPassword)
                            .addComponent(jLabelUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLogearse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUsuario)
                                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxVerPassword)))))
                .addContainerGap())
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxVerPassword))
                .addGap(18, 18, 18)
                .addComponent(jButtonLogearse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabelRegistro)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogearseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogearseActionPerformed
        try {
            UsuarioControlador.compruebaUsuarioconPassword();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error con la bdd contacte con el administrador", "Error inesperado", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLogearseActionPerformed
    /*
     * Esta accion occure cuando el fieldUusuario gana el focus  
     * flagNombre está en false. si es false el jTextFieldUsuario se pondrá como texto vacio y el color de fuente
     * pasará a ser negro. 
     * flagNombre pasa a ser true.  
     */
    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        UsuarioControladorEventos.VaciarCampos(evt, 0);
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    /*
     *Esta accion occurre cuando se pierde el focus en el fieldUsuario.
     *comprueba que si el campo jtextField está vacío. si está vacío se pone el texto como usuario y pasa el color a gris.
     *el flagNombre pasa a ser false.
     */
    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
        UsuarioControladorEventos.RellenarCampos(evt, 0);
         
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost
    /*
     *Este campo se ejecuta cuando el checkbox es presionado.
     *si está seleccionado los caracteres y flagPasword es true se pondrán con texto plano. en cambio, los caracteres saldrán en forma de
     *asteríscos. 
     */

    private void jCheckBoxVerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVerPasswordActionPerformed
        UsuarioControladorEventos.MostrarOcultarContraseña(evt);
    }//GEN-LAST:event_jCheckBoxVerPasswordActionPerformed
/*
 Esta accion se ejecuta cuando el jPasswordFieldPassword tiene el foco.   
 cuando flagPassword es false el texto pasa a estar vacío, pasando a ser los caracteres de color negro y 
 a verse como asteriscos. el flagPassword se pondrá true.
 si el checkbox esta selecccionado los caracteres se verán en texto plano.
 */

    private void jPasswordFieldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusGained
       UsuarioControladorEventos.VaciarCampos(evt, 1);
    }//GEN-LAST:event_jPasswordFieldPasswordFocusGained

    /*
     si el passwordfield está vacío se pondrá con caracteres de texto, pondrá el texto Password y el color en gris.
    
     */

    private void jPasswordFieldPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordFocusLost
        UsuarioControladorEventos.RellenarCampos(evt, 1);
    }//GEN-LAST:event_jPasswordFieldPasswordFocusLost

    private void jLabelRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseClicked
        
       UsuarioControlador.AbrirVistaRegistro();  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRegistroMouseClicked

    private void jLabelRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_jLabelRegistroMouseEntered

    private void jLabelRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegistroMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_jLabelRegistroMouseExited

    private void jButtonLogearseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogearseMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogearseMouseEntered

    private void jButtonLogearseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogearseMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogearseMouseExited

    private void jCheckBoxVerPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxVerPasswordMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxVerPasswordMouseEntered

    private void jCheckBoxVerPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxVerPasswordMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxVerPasswordMouseExited

    private void jPasswordFieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordKeyPressed
        if (evt.getKeyChar() == evt.VK_ENTER){
            try {
            UsuarioControlador.compruebaUsuarioconPassword();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error con la bdd contacte con el administrador", "Error inesperado", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
      }  // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordKeyPressed

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        if (evt.getKeyChar() == evt.VK_ENTER){
            
            jPasswordFieldPassword.requestFocus();
        
      }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Login loginCreado= new Login();
                    loginCreado.setLocationRelativeTo(null);
                    loginCreado.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogearse;
    private javax.swing.JCheckBox jCheckBoxVerPassword;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getjTextFieldUsuario() {
        return jTextFieldUsuario;
    }

    public void setjTextFieldUsuario(javax.swing.JTextField jTextFieldUsuario) {
        this.jTextFieldUsuario = jTextFieldUsuario;
    }

    public JPasswordField getjPasswordFieldPassword() {
        return jPasswordFieldPassword;
    }

    public void setjPasswordFieldPassword(JPasswordField jPasswordFieldPassword) {
        this.jPasswordFieldPassword = jPasswordFieldPassword;
    }

   
       public boolean getFlagNombre() {
        return flagNombre;
    }

    public void setFlagNombre(boolean flagNombre) {
        this.flagNombre = flagNombre;
    }

    public boolean getFlagPassword() {
        return flagPassword;
    }

    public void setFlagPassword(boolean flagPassword) {
        this.flagPassword = flagPassword;
    }

    public JCheckBox getjCheckBoxVerPassword() {
        return jCheckBoxVerPassword;
    }

    public void setjCheckBoxVerPassword(JCheckBox jCheckBoxVerPassword) {
        this.jCheckBoxVerPassword = jCheckBoxVerPassword;
    }

  
    
    
}
