/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hobbyteca.vista;

import hobbyteca.controlador.ControladorVerVideojuego;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author jesus
 */
public class VerVideojuego extends javax.swing.JDialog {
    /**
     * Creates new form VerPelicula
     */
    private final ControladorVerVideojuego controladorVerVideojuego;
    public VerVideojuego(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controladorVerVideojuego =new ControladorVerVideojuego(this);
        controladorVerVideojuego.rellenarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRecomendar = new javax.swing.ButtonGroup();
        buttonGroupValoracion = new javax.swing.ButtonGroup();
        buttonGroupVisualizado = new javax.swing.ButtonGroup();
        buttonGroupValoracionPersonal = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDesarrolladora = new javax.swing.JLabel();
        jLabelTextDesarrolladora = new javax.swing.JLabel();
        jLabelDistribuidora = new javax.swing.JLabel();
        jLabelTextProductora = new javax.swing.JLabel();
        jLabelLanzamiento = new javax.swing.JLabel();
        jLabelTextLanzamiento = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelTextGenero = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jScrollPaneDescripcion = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jLabelValoracionMedia = new javax.swing.JLabel();
        jLabelTextValoracionMedia = new javax.swing.JLabel();
        jLabelValoracionPersonal = new javax.swing.JLabel();
        jRadioButtonValor0 = new javax.swing.JRadioButton();
        jRadioButtonValor1 = new javax.swing.JRadioButton();
        jRadioButtonValor2 = new javax.swing.JRadioButton();
        jRadioButtonValor3 = new javax.swing.JRadioButton();
        jRadioButtonValor4 = new javax.swing.JRadioButton();
        jRadioButtonValor5 = new javax.swing.JRadioButton();
        jLabelVisualizado = new javax.swing.JLabel();
        jRadioButtonVisualizadoSi = new javax.swing.JRadioButton();
        jRadioButtonVisualizadoNo = new javax.swing.JRadioButton();
        jLabelRecomendar = new javax.swing.JLabel();
        jRadioButtonRecomendarSi = new javax.swing.JRadioButton();
        jRadioButtonRecomendarNo = new javax.swing.JRadioButton();
        jLabelTrailer = new javax.swing.JLabel();
        jScrollPaneTrailer = new javax.swing.JScrollPane();
        jTextAreaTrailer = new javax.swing.JTextArea();
        jButtonAplicar = new javax.swing.JButton();
        jLabelPlataforma = new javax.swing.JLabel();
        jLabelTextPlataforma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VideoJuego");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("TITULO");

        jLabelDesarrolladora.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelDesarrolladora.setText("Desarrolladora:");

        jLabelTextDesarrolladora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTextDesarrolladora.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTextDesarrolladora.setText("jLabel1");

        jLabelDistribuidora.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelDistribuidora.setText("Distribuidora:");

        jLabelTextProductora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTextProductora.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTextProductora.setText("jLabel2");

        jLabelLanzamiento.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelLanzamiento.setText("Lanzamiento:");

        jLabelTextLanzamiento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTextLanzamiento.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTextLanzamiento.setText("jLabel3");

        jLabelGenero.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelGenero.setText("Género:");

        jLabelTextGenero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTextGenero.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTextGenero.setText("jLabel4");

        jLabelDescripcion.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelDescripcion.setText("Descripción:");

        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextAreaDescripcion.setForeground(new java.awt.Color(0, 0, 255));
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jScrollPaneDescripcion.setViewportView(jTextAreaDescripcion);

        jLabelValoracionMedia.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelValoracionMedia.setText("Valoración Media:");

        jLabelTextValoracionMedia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTextValoracionMedia.setForeground(new java.awt.Color(0, 102, 0));
        jLabelTextValoracionMedia.setText("0/5");

        jLabelValoracionPersonal.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelValoracionPersonal.setText("Valoración Personal:");

        buttonGroupValoracion.add(jRadioButtonValor0);
        jRadioButtonValor0.setText("0");

        buttonGroupValoracion.add(jRadioButtonValor1);
        jRadioButtonValor1.setText("1");

        buttonGroupValoracion.add(jRadioButtonValor2);
        jRadioButtonValor2.setText("2");

        buttonGroupValoracion.add(jRadioButtonValor3);
        jRadioButtonValor3.setText("3");

        buttonGroupValoracion.add(jRadioButtonValor4);
        jRadioButtonValor4.setText("4");

        buttonGroupValoracion.add(jRadioButtonValor5);
        jRadioButtonValor5.setText("5");

        jLabelVisualizado.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelVisualizado.setText("Jugado:");

        buttonGroupVisualizado.add(jRadioButtonVisualizadoSi);
        jRadioButtonVisualizadoSi.setText("Sí");

        buttonGroupVisualizado.add(jRadioButtonVisualizadoNo);
        jRadioButtonVisualizadoNo.setText("No");

        jLabelRecomendar.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelRecomendar.setText("Recomendar:");

        buttonGroupRecomendar.add(jRadioButtonRecomendarSi);
        jRadioButtonRecomendarSi.setText("Sí");

        buttonGroupRecomendar.add(jRadioButtonRecomendarNo);
        jRadioButtonRecomendarNo.setText("No");

        jLabelTrailer.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelTrailer.setText("Trailer:");

        jScrollPaneTrailer.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPaneTrailer.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaTrailer.setEditable(false);
        jTextAreaTrailer.setColumns(20);
        jTextAreaTrailer.setForeground(new java.awt.Color(0, 0, 255));
        jTextAreaTrailer.setRows(5);
        jScrollPaneTrailer.setViewportView(jTextAreaTrailer);

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        jLabelPlataforma.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabelPlataforma.setText("Plataforma:");

        jLabelTextPlataforma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTextPlataforma.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTextPlataforma.setText("jLabel5");

        javax.swing.GroupLayout buttonGroupValoracionPersonalLayout = new javax.swing.GroupLayout(buttonGroupValoracionPersonal);
        buttonGroupValoracionPersonal.setLayout(buttonGroupValoracionPersonalLayout);
        buttonGroupValoracionPersonalLayout.setHorizontalGroup(
            buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                        .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLanzamiento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDistribuidora, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelDesarrolladora, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPlataforma, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelGenero, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(47, 47, 47)
                                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTextDesarrolladora)
                                    .addComponent(jLabelTextProductora)
                                    .addComponent(jLabelTextLanzamiento)
                                    .addComponent(jLabelTextGenero)
                                    .addComponent(jLabelTextPlataforma)))
                            .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabelDescripcion)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                    .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelValoracionPersonal, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelValoracionMedia, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelTrailer, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelRecomendar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelVisualizado, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                                    .addComponent(jRadioButtonVisualizadoSi)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jRadioButtonVisualizadoNo))
                                                .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                                    .addComponent(jRadioButtonValor0)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jRadioButtonValor1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jRadioButtonValor2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jRadioButtonValor3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jRadioButtonValor4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jRadioButtonValor5))
                                                .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                                    .addComponent(jRadioButtonRecomendarSi)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jRadioButtonRecomendarNo))
                                                .addComponent(jLabelTextValoracionMedia)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonGroupValoracionPersonalLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPaneTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(jButtonAplicar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonGroupValoracionPersonalLayout.setVerticalGroup(
            buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelTextDesarrolladora, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelDesarrolladora))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDistribuidora)
                    .addComponent(jLabelTextProductora))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLanzamiento)
                    .addComponent(jLabelTextLanzamiento))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero)
                    .addComponent(jLabelTextGenero))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlataforma)
                    .addComponent(jLabelTextPlataforma))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buttonGroupValoracionPersonalLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelDescripcion)))
                .addGap(35, 35, 35)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextValoracionMedia)
                    .addComponent(jLabelValoracionMedia))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValoracionPersonal)
                    .addComponent(jRadioButtonValor0)
                    .addComponent(jRadioButtonValor1)
                    .addComponent(jRadioButtonValor2)
                    .addComponent(jRadioButtonValor3)
                    .addComponent(jRadioButtonValor4)
                    .addComponent(jRadioButtonValor5))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVisualizado)
                    .addComponent(jRadioButtonVisualizadoSi)
                    .addComponent(jRadioButtonVisualizadoNo))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRecomendar)
                    .addComponent(jRadioButtonRecomendarSi)
                    .addComponent(jRadioButtonRecomendarNo))
                .addGap(18, 18, 18)
                .addGroup(buttonGroupValoracionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrailer))
                .addGap(83, 83, 83)
                .addComponent(jButtonAplicar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonGroupValoracionPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonGroupValoracionPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
       int valoracion=Integer.parseInt(getSelectedButtonText(buttonGroupValoracion));
       int recomendado;  
       int visto;
        if( getSelectedButtonText(buttonGroupRecomendar).equals("No") ){
        recomendado=0;
        }else{
        recomendado=1;
        }
         if( getSelectedButtonText(buttonGroupVisualizado).equals("No") ){
        visto=0;
        }else{
        visto=1;
        }
        try { 
            controladorVerVideojuego.guardarActualizacion(valoracion,recomendado, visto);
            JOptionPane.showMessageDialog(this, "Se han guardado los cambios correctamente","Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error con la bdd contacte con el administrador", "Error inesperado", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(VerVideojuego.class.getName()).log(Level.SEVERE, null, ex);
        }
        controladorVerVideojuego.rellenarDatos();
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerVideojuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerVideojuego dialog = new VerVideojuego(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public ButtonGroup getButtonGroupRecomendar() {
        return buttonGroupRecomendar;
    }

    public void setButtonGroupRecomendar(ButtonGroup buttonGroupRecomendar) {
        this.buttonGroupRecomendar = buttonGroupRecomendar;
    }

    public ButtonGroup getButtonGroupValoracion() {
        return buttonGroupValoracion;
    }

    public void setButtonGroupValoracion(ButtonGroup buttonGroupValoracion) {
        this.buttonGroupValoracion = buttonGroupValoracion;
    }

    public JPanel getButtonGroupValoracionPersonal() {
        return buttonGroupValoracionPersonal;
    }

    public void setButtonGroupValoracionPersonal(JPanel buttonGroupValoracionPersonal) {
        this.buttonGroupValoracionPersonal = buttonGroupValoracionPersonal;
    }

    public ButtonGroup getButtonGroupVisualizado() {
        return buttonGroupVisualizado;
    }

    public void setButtonGroupVisualizado(ButtonGroup buttonGroupVisualizado) {
        this.buttonGroupVisualizado = buttonGroupVisualizado;
    }

    public JButton getjButtonAplicar() {
        return jButtonAplicar;
    }

    public void setjButtonAplicar(JButton jButtonAplicar) {
        this.jButtonAplicar = jButtonAplicar;
    }

    public JLabel getjLabelDesarrolladora() {
        return jLabelDesarrolladora;
    }

    public void setjLabelDesarrolladora(JLabel jLabelDesarrolladora) {
        this.jLabelDesarrolladora = jLabelDesarrolladora;
    }

    public JLabel getjLabelDescripcion() {
        return jLabelDescripcion;
    }

    public void setjLabelDescripcion(JLabel jLabelDescripcion) {
        this.jLabelDescripcion = jLabelDescripcion;
    }

    public JLabel getjLabelDistribuidora() {
        return jLabelDistribuidora;
    }

    public void setjLabelDistribuidora(JLabel jLabelDistribuidora) {
        this.jLabelDistribuidora = jLabelDistribuidora;
    }

    public JLabel getjLabelGenero() {
        return jLabelGenero;
    }

    public void setjLabelGenero(JLabel jLabelGenero) {
        this.jLabelGenero = jLabelGenero;
    }

    public JLabel getjLabelLanzamiento() {
        return jLabelLanzamiento;
    }

    public void setjLabelLanzamiento(JLabel jLabelLanzamiento) {
        this.jLabelLanzamiento = jLabelLanzamiento;
    }

    public JLabel getjLabelPlataforma() {
        return jLabelPlataforma;
    }

    public void setjLabelPlataforma(JLabel jLabelPlataforma) {
        this.jLabelPlataforma = jLabelPlataforma;
    }

    public JLabel getjLabelRecomendar() {
        return jLabelRecomendar;
    }

    public void setjLabelRecomendar(JLabel jLabelRecomendar) {
        this.jLabelRecomendar = jLabelRecomendar;
    }

    public JLabel getjLabelTextDesarrolladora() {
        return jLabelTextDesarrolladora;
    }

    public void setjLabelTextDesarrolladora(JLabel jLabelTextDesarrolladora) {
        this.jLabelTextDesarrolladora = jLabelTextDesarrolladora;
    }

    public JLabel getjLabelTextGenero() {
        return jLabelTextGenero;
    }

    public void setjLabelTextGenero(JLabel jLabelTextGenero) {
        this.jLabelTextGenero = jLabelTextGenero;
    }

    public JLabel getjLabelTextLanzamiento() {
        return jLabelTextLanzamiento;
    }

    public void setjLabelTextLanzamiento(JLabel jLabelTextLanzamiento) {
        this.jLabelTextLanzamiento = jLabelTextLanzamiento;
    }

    public JLabel getjLabelTextPlataforma() {
        return jLabelTextPlataforma;
    }

    public void setjLabelTextPlataforma(JLabel jLabelTextPlataforma) {
        this.jLabelTextPlataforma = jLabelTextPlataforma;
    }

    public JLabel getjLabelTextProductora() {
        return jLabelTextProductora;
    }

    public void setjLabelTextProductora(JLabel jLabelTextProductora) {
        this.jLabelTextProductora = jLabelTextProductora;
    }

    public JLabel getjLabelTextValoracionMedia() {
        return jLabelTextValoracionMedia;
    }

    public void setjLabelTextValoracionMedia(JLabel jLabelTextValoracionMedia) {
        this.jLabelTextValoracionMedia = jLabelTextValoracionMedia;
    }

    public JLabel getjLabelTitulo() {
        return jLabelTitulo;
    }

    public void setjLabelTitulo(JLabel jLabelTitulo) {
        this.jLabelTitulo = jLabelTitulo;
    }

    public JLabel getjLabelTrailer() {
        return jLabelTrailer;
    }

    public void setjLabelTrailer(JLabel jLabelTrailer) {
        this.jLabelTrailer = jLabelTrailer;
    }

    public JLabel getjLabelValoracionMedia() {
        return jLabelValoracionMedia;
    }

    public void setjLabelValoracionMedia(JLabel jLabelValoracionMedia) {
        this.jLabelValoracionMedia = jLabelValoracionMedia;
    }

    public JLabel getjLabelValoracionPersonal() {
        return jLabelValoracionPersonal;
    }

    public void setjLabelValoracionPersonal(JLabel jLabelValoracionPersonal) {
        this.jLabelValoracionPersonal = jLabelValoracionPersonal;
    }

    public JLabel getjLabelVisualizado() {
        return jLabelVisualizado;
    }

    public void setjLabelVisualizado(JLabel jLabelVisualizado) {
        this.jLabelVisualizado = jLabelVisualizado;
    }

    public JRadioButton getjRadioButtonRecomendarNo() {
        return jRadioButtonRecomendarNo;
    }

    public void setjRadioButtonRecomendarNo(JRadioButton jRadioButtonRecomendarNo) {
        this.jRadioButtonRecomendarNo = jRadioButtonRecomendarNo;
    }

    public JRadioButton getjRadioButtonRecomendarSi() {
        return jRadioButtonRecomendarSi;
    }

    public void setjRadioButtonRecomendarSi(JRadioButton jRadioButtonRecomendarSi) {
        this.jRadioButtonRecomendarSi = jRadioButtonRecomendarSi;
    }

    public JRadioButton getjRadioButtonValor0() {
        return jRadioButtonValor0;
    }

    public void setjRadioButtonValor0(JRadioButton jRadioButtonValor0) {
        this.jRadioButtonValor0 = jRadioButtonValor0;
    }

    public JRadioButton getjRadioButtonValor1() {
        return jRadioButtonValor1;
    }

    public void setjRadioButtonValor1(JRadioButton jRadioButtonValor1) {
        this.jRadioButtonValor1 = jRadioButtonValor1;
    }

    public JRadioButton getjRadioButtonValor2() {
        return jRadioButtonValor2;
    }

    public void setjRadioButtonValor2(JRadioButton jRadioButtonValor2) {
        this.jRadioButtonValor2 = jRadioButtonValor2;
    }

    public JRadioButton getjRadioButtonValor3() {
        return jRadioButtonValor3;
    }

    public void setjRadioButtonValor3(JRadioButton jRadioButtonValor3) {
        this.jRadioButtonValor3 = jRadioButtonValor3;
    }

    public JRadioButton getjRadioButtonValor4() {
        return jRadioButtonValor4;
    }

    public void setjRadioButtonValor4(JRadioButton jRadioButtonValor4) {
        this.jRadioButtonValor4 = jRadioButtonValor4;
    }

    public JRadioButton getjRadioButtonValor5() {
        return jRadioButtonValor5;
    }

    public void setjRadioButtonValor5(JRadioButton jRadioButtonValor5) {
        this.jRadioButtonValor5 = jRadioButtonValor5;
    }

    public JRadioButton getjRadioButtonVisualizadoNo() {
        return jRadioButtonVisualizadoNo;
    }

    public void setjRadioButtonVisualizadoNo(JRadioButton jRadioButtonVisualizadoNo) {
        this.jRadioButtonVisualizadoNo = jRadioButtonVisualizadoNo;
    }

    public JRadioButton getjRadioButtonVisualizadoSi() {
        return jRadioButtonVisualizadoSi;
    }

    public void setjRadioButtonVisualizadoSi(JRadioButton jRadioButtonVisualizadoSi) {
        this.jRadioButtonVisualizadoSi = jRadioButtonVisualizadoSi;
    }

    public JScrollPane getjScrollPaneDescripcion() {
        return jScrollPaneDescripcion;
    }

    public void setjScrollPaneDescripcion(JScrollPane jScrollPaneDescripcion) {
        this.jScrollPaneDescripcion = jScrollPaneDescripcion;
    }

    public JScrollPane getjScrollPaneTrailer() {
        return jScrollPaneTrailer;
    }

    public void setjScrollPaneTrailer(JScrollPane jScrollPaneTrailer) {
        this.jScrollPaneTrailer = jScrollPaneTrailer;
    }

    public JTextArea getjTextAreaDescripcion() {
        return jTextAreaDescripcion;
    }

    public void setjTextAreaDescripcion(JTextArea jTextAreaDescripcion) {
        this.jTextAreaDescripcion = jTextAreaDescripcion;
    }

    public JTextArea getjTextAreaTrailer() {
        return jTextAreaTrailer;
    }

    public void setjTextAreaTrailer(JTextArea jTextAreaTrailer) {
        this.jTextAreaTrailer = jTextAreaTrailer;
    }



    
 public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRecomendar;
    private javax.swing.ButtonGroup buttonGroupValoracion;
    private javax.swing.JPanel buttonGroupValoracionPersonal;
    private javax.swing.ButtonGroup buttonGroupVisualizado;
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JLabel jLabelDesarrolladora;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelDistribuidora;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLanzamiento;
    private javax.swing.JLabel jLabelPlataforma;
    private javax.swing.JLabel jLabelRecomendar;
    private javax.swing.JLabel jLabelTextDesarrolladora;
    private javax.swing.JLabel jLabelTextGenero;
    private javax.swing.JLabel jLabelTextLanzamiento;
    private javax.swing.JLabel jLabelTextPlataforma;
    private javax.swing.JLabel jLabelTextProductora;
    private javax.swing.JLabel jLabelTextValoracionMedia;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTrailer;
    private javax.swing.JLabel jLabelValoracionMedia;
    private javax.swing.JLabel jLabelValoracionPersonal;
    private javax.swing.JLabel jLabelVisualizado;
    private javax.swing.JRadioButton jRadioButtonRecomendarNo;
    private javax.swing.JRadioButton jRadioButtonRecomendarSi;
    private javax.swing.JRadioButton jRadioButtonValor0;
    private javax.swing.JRadioButton jRadioButtonValor1;
    private javax.swing.JRadioButton jRadioButtonValor2;
    private javax.swing.JRadioButton jRadioButtonValor3;
    private javax.swing.JRadioButton jRadioButtonValor4;
    private javax.swing.JRadioButton jRadioButtonValor5;
    private javax.swing.JRadioButton jRadioButtonVisualizadoNo;
    private javax.swing.JRadioButton jRadioButtonVisualizadoSi;
    private javax.swing.JScrollPane jScrollPaneDescripcion;
    private javax.swing.JScrollPane jScrollPaneTrailer;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextArea jTextAreaTrailer;
    // End of variables declaration//GEN-END:variables
}
